### ISSUE TITLE
create scrapper script

### ISSUE THREAD

**Issue by haniagibus** [agatherat/BI-project-winx-club#2]
automatically read and save locally information and data from chosen online shop

**Comment by michellamilecka** [comment]
Added script to scrape product categories and subcategories from a website using urllib.request for fetching page content, BeautifulSoup for parsing HTML, and json for saving the data in a JSON format. For each category we use recursion to fetch all the subcategories.

**Comment by michellamilecka** [comment]
Created scripts that can convert generated json files with categories and products from the website, and can be imported into prestashop in csv format.
